services:
  db:
    image: postgres:15-alpine
    container_name: paykey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paykey
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paykey-network

  redis:
    image: redis:7-alpine
    container_name: paykey_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paykey-network

  backend:
    image: node:20-alpine
    container_name: paykey_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=paykey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # M-Pesa API Configuration
      # Sandbox (default): https://sandbox.safaricom.co.ke
      # Live/Production:   https://api.safaricom.co.ke
      - MPESA_BASE_URL=https://sandbox.safaricom.co.ke
      # M-Pesa Sandbox Credentials
      - MPESA_CONSUMER_KEY=UyNcT5SZGGdCBAyzJdcpTR53Lujxyu2rW5kcJ9IVqFjGdqLh
      - MPESA_CONSUMER_SECRET=gPTUyt9gyzTUyRLGhdkNEpFwFFpjsIVIPunuqhI6rR4yolL6Y1yFURnOkq1d3wMv
      - MPESA_PASSKEY=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
      - MPESA_SHORTCODE=174379
      - MPESA_B2C_SHORTCODE=600981
      - MPESA_INITIATOR_NAME=testapi
      - MPESA_SECURITY_CREDENTIAL=n5Vo+6OHz7F+IbfBBu1SHR1/dGRhSiqC9FITNLFKhG5vDWwhL5iJinc6m015n7DpmI4juwdSaQr6IXWzo7/Jc4lPrM+QJoEFjV2nkeCvGiW1Ayme9gr7e3A7O8Xfox1Qz6D3dEdDQ8SGQwsfww/0YLB7Jr7ZeIBwqpisyjJ4+ypUIKPdiP3/k77voiehSaSHHUxczT6L29xpDGFwVXTDh5ZMkZ72uu1AXVcHVM3ht7DoSPUmkQ70GI6l3l7GedYrfsCOuQzcUI/whPyNOmuQ467j35+zH5coH8cKagehGcQuI5Ghf2/4HQfUpme45KI1wK6gvhKBqH1MrgAGz26Tdw==
      - MPESA_CALLBACK_URL=https://dictatorily-contrarious-darby.ngrok-free.dev
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install -g npm@latest && npm install && npm run build && npm run typeorm:migration:run && npm run start:dev"
    networks:
      - paykey-network

volumes:
  postgres_data:
  redis_data:


networks:
  paykey-network:
    driver: bridge
