services:
  db:
    image: postgres:17-alpine
    container_name: paykey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tina76
      POSTGRES_DB: paykey
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paykey-network

  redis:
    image: redis:7-alpine
    container_name: paykey_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paykey-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: paykey_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Tina76
      - DB_NAME=paykey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # M-Pesa API Configuration
      # Sandbox (default): https://sandbox.safaricom.co.ke
      # Live/Production:   https://api.safaricom.co.ke
      #MPESA_BASE_URL=https://sandbox.safaricom.co.ke
      # M-Pesa Sandbox Credentials
      # MPESA_CONSUMER_KEY=UyNcT5SZGGdCBAyzJdcpTR53Lujxyu2rW5kcJ9IVqFjGdqLh
      # MPESA_CONSUMER_SECRET=YOUR_MPESA_CONSUMER_SECRET
      # MPESA_PASSKEY=YOUR_MPESA_PASSKEY
      # MPESA_SHORTCODE=174379
      # MPESA_B2C_SHORTCODE=600981
      # MPESA_INITIATOR_NAME=testapi
      # MPESA_SECURITY_CREDENTIAL=YOUR_MPESA_SECURITY_CREDENTIAL
      # MPESA_CALLBACK_URL=https://dictatorily-contrarious-darby.ngrok-free.dev
      # Stripe Configuration
      # STRIPE_PUBLISHABLE_KEY=pk_test_51QwpabCEEEC74IBu4Hfv55pvIFddcqRw4AYyVeexIsE2ZO32yRnfAnQKJb6184IFMAHWrXf09CcNYpDYG7kru3At00eSn5kILz
      # STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY
      # STRIPE_WEBHOOK_SECRET=YOUR_STRIPE_WEBHOOK_SECRET
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    working_dir: /app
    volumes:
      # - ./backend:/app:cached  <-- REMOVED TO FIX ERROR -35
      - ./backend/uploads:/app/uploads
      - ./backend/exports:/app/exports
      - /app/node_modules
    command: sh -c "npm run start:dev"
    networks:
      - paykey-network

  website:
    image: node:20-alpine
    container_name: paykey_website
    ports:
      - "5173:5173"
    volumes:
      - ./website:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:3000
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - paykey-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: paykey_ngrok
    restart: unless-stopped
    command: http backend:3000 --domain=dictatorily-contrarious-darby.ngrok-free.dev
    environment:
      - NGROK_AUTHTOKEN=34Jv8kOgcr1lyc2ljBS77zCxn6N_4bub1wQ9JqVoyp92HVomw
    ports:
      - "4040:4040"
    networks:
      - paykey-network
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:


networks:
  paykey-network:
    driver: bridge
