services:
  db:
    image: postgres:17-alpine
    container_name: paykey_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: paykey
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - paykey-network

  redis:
    image: redis:7-alpine
    container_name: paykey_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - paykey-network

  backend:
    image: node:20-alpine
    container_name: paykey_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=paykey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # M-Pesa API Configuration
      # Sandbox (default): https://sandbox.safaricom.co.ke
      # Live/Production:   https://api.safaricom.co.ke
      #MPESA_BASE_URL=https://sandbox.safaricom.co.ke
      # M-Pesa Sandbox Credentials
      # MPESA_CONSUMER_KEY=UyNcT5SZGGdCBAyzJdcpTR53Lujxyu2rW5kcJ9IVqFjGdqLh
      # MPESA_CONSUMER_SECRET=YOUR_MPESA_CONSUMER_SECRET
      # MPESA_PASSKEY=YOUR_MPESA_PASSKEY
      # MPESA_SHORTCODE=174379
      # MPESA_B2C_SHORTCODE=600981
      # MPESA_INITIATOR_NAME=testapi
      # MPESA_SECURITY_CREDENTIAL=YOUR_MPESA_SECURITY_CREDENTIAL
      # MPESA_CALLBACK_URL=https://dictatorily-contrarious-darby.ngrok-free.dev
      # Stripe Configuration
      # STRIPE_PUBLISHABLE_KEY=pk_test_51QwpabCEEEC74IBu4Hfv55pvIFddcqRw4AYyVeexIsE2ZO32yRnfAnQKJb6184IFMAHWrXf09CcNYpDYG7kru3At00eSn5kILz
      # STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY
      # STRIPE_WEBHOOK_SECRET=YOUR_STRIPE_WEBHOOK_SECRET
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install -g npm@11.7.0 && npm install && npm run typeorm:migration:run && npm run seed && npm run start:dev"
    networks:
      - paykey-network

volumes:
  postgres_data:
  redis_data:


networks:
  paykey-network:
    driver: bridge
